<!-- 费用列表 -->
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"
%>
<div>
	<div>
		<table id="tbExpenseRate" class="table table-striped table-hover" style="width: 100%!important;">
			<thead>
				<tr>
					<th>
						编号
					</th>
					<th>
						费用类型
					</th>
					<th>
						费用名称
					</th>
					<th>
						标准费率（%）
					</th>
					<th>
						实际费率（%）
					</th>
					<th>
						标准收费
					</th>
					<th>
						实际收费
					</th>
					<th>
						提交时间
					</th>
					<th>
						操作
					</th>
				</tr>
			</thead>
			<tbody>
			</tbody>
		</table>
	</div>
</div>